import argparse

def initialize():
    """Initialize the code by taking arguments from the command line

    Parameters
    ----------
    There are no parameters passed to this function

    Returns
    -------
    args : type: argparse namespace

    """
    parser = argparse.ArgumentParser(
        description=' This program takes a certain column of the data'
        ' from stdin generated by gen_data.sh given the column number'
        ' and plot a boxplot or a histogram or both given the type of'
        ' the plot specified by the user. Finally, the plot will be'
        ' saved with the specified filename',
        prog='viz.py'
    )
    parser.add_argument('-t',
                        '--type',
                        type=str,
                        help='The type of the plot to be generated',
                        required=True)

    parser.add_argument('-n',
                        '--output_name',
                        type=str,
                        help='The file name of the input file, which should be'
                        ' a tab-separated file of integers.',
                        required=True)

    parser.add_argument('-c',
                        '--col_num',
                        type=str,
                        help='The column number',
                        required=True)

    args = parser
    # or we can return parser.parse_args() and use args = initialize() in the
    # main function instead

    return args

def main():










if __name__ == '__main__':
    main()
